### ISSUE TITLE
关于某关于zfs dualboot文章请教一下

### ISSUE THREAD

**Issue by zengjiapei3000** [Pinghigh/pinghigh.github.io#3]
你好，感谢你的文章，我参考了一下这篇：https://pinghigh.github.io/2022/11/28/2022-11-28-ZFSBootMenu/
里面的双系统中的另一个系统是windows10吗

**Comment by Pinghigh** [comment]
最新的博文在 https://blog.tibrella.top/post/zbm-guide

双系统里面另一个系统是任意一个可以通过 UEFI 方式引导的系统，Win10 是可以的（
